// from discord api docs

const defaultIntents: string[] = [
    "READY",
    "RESUMED",
    "VOICE_SERVER_UPDATE",
    "USER_UPDATE",
    "APPLICATION_COMMAND_CREATE",
    "APPLICATION_COMMAND_UPDATE",
    "APPLICATION_COMMAND_DELETE",
    "INTERACTION_CREATE"
]

const intents : {[key: string]: string[]} = {
  GUILDS: [
    "GUILD_CREATE",
    "GUILD_UPDATE",
    "GUILD_DELETE",
    "GUILD_ROLE_CREATE",
    "GUILD_ROLE_UPDATE",
    "GUILD_ROLE_DELETE",
    "CHANNEL_CREATE",
    "CHANNEL_UPDATE",
    "CHANNEL_DELETE",
    "CHANNEL_PINS_UPDATE",
    "THREAD_CREATE",
    "THREAD_UPDATE",
    "THREAD_DELETE",
    "THREAD_LIST_SYNC",
    "THREAD_MEMBER_UPDATE",
    "THREAD_MEMBERS_UPDATE *",
    "STAGE_INSTANCE_CREATE",
    "STAGE_INSTANCE_UPDATE",
    "STAGE_INSTANCE_DELETE"
  ],

  GUILD_MEMBERS: [
    "GUILD_MEMBER_ADD",
    "GUILD_MEMBER_UPDATE",
    "GUILD_MEMBER_REMOVE",
    "THREAD_MEMBERS_UPDATE *",
  ], 

  GUILD_BANS: [
    "GUILD_BAN_ADD",
    "GUILD_BAN_REMOVE",
  ],

  GUILD_EMOJIS_AND_STICKERS: [
    "GUILD_EMOJIS_UPDATE",
    "GUILD_STICKERS_UPDATE",
  ],

  GUILD_INTEGRATIONS: [
    "GUILD_INTEGRATIONS_UPDATE",
    "INTEGRATION_CREATE",
    "INTEGRATION_UPDATE",
    "INTEGRATION_DELETE",
  ],

  GUILD_WEBHOOKS: [
    "WEBHOOKS_UPDATE"
  ],

  GUILD_INVITES: [
    "INVITE_CREATE",
    "INVITE_DELETE",
  ],

  GUILD_VOICE_STATES: [
    "VOICE_STATE_UPDATE"
  ],

  GUILD_PRESENCES: [
    "PRESENCE_UPDATE"
  ],

  GUILD_MESSAGES: [
    "MESSAGE_CREATE",
    "MESSAGE_UPDATE",
    "MESSAGE_DELETE",
    "MESSAGE_DELETE_BULK",
  ],

  GUILD_MESSAGE_REACTIONS: [
    "MESSAGE_REACTION_ADD",
    "MESSAGE_REACTION_REMOVE",
    "MESSAGE_REACTION_REMOVE_ALL",
    "MESSAGE_REACTION_REMOVE_EMOJI",
  ],

  GUILD_MESSAGE_TYPING: [
    "TYPING_START"
  ],

  DIRECT_MESSAGES: [
    "MESSAGE_CREATE",
    "MESSAGE_UPDATE",
    "MESSAGE_DELETE",
    "CHANNEL_PINS_UPDATE",
  ],

  DIRECT_MESSAGE_REACTIONS: [
    "MESSAGE_REACTION_ADD",
    "MESSAGE_REACTION_REMOVE",
    "MESSAGE_REACTION_REMOVE_ALL",
    "MESSAGE_REACTION_REMOVE_EMOJI",
  ],

  DIRECT_MESSAGE_TYPING: [
    "TYPING_START"
  ]
}

export { defaultIntents, intents }